version: '2'

services:

  front:
    image: front
    ports:
      - 80:80        
    labels:
      - "traefik.http.routers.front.rule=Host(`front.fullstak.pro`)"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=le"            
      - "traefik.http.routers.front.service=front"
      # - "traefik.http.services.front.loadbalancer.server.port=3000"

    networks:
      - gooya
    restart: always        

networks:
  gooya:
    external: true